### ISSUE TITLE
Error when called from CLI only

### ISSUE THREAD

**Issue by DavidUdell** [DavidUdell/sparse_circuit_discovery#116]
```
Exception ignored in: <function AGraph.__del__ at 0x7ff14daed2d0>
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/pygraphviz/agraph.py", line 295, in __del__
  File "/opt/conda/lib/python3.10/site-packages/pygraphviz/agraph.py", line 1012, in _close_handle
TypeError: 'NoneType' object is not callable
```

**Comment by DavidUdell** [comment]
I think this does not affect functionality. Still annoying.

**Comment by DavidUdell** [comment]
Cleanup error ignored; not important, I think.
