### ISSUE TITLE
Despite updating the https headers, I'm still getting too many redirects errors on _large_ runs

### ISSUE THREAD

**Issue by DavidUdell** [DavidUdell/sparse_circuit_discovery#130]

**Comment by DavidUdell** [comment]
Irregularly--not on every large run.

**Comment by DavidUdell** [comment]
```
Traceback (most recent call last):
  File "/root/sparse_circuit_discovery/sparse_coding/interp_tools/grad_graph.py", line 529, in <module>
    label=label_highlighting(
  File "/root/sparse_circuit_discovery/sparse_coding/interp_tools/utils/graphs.py", line 216, in label_highlighting
    label += neuronpedia_api(
  File "/root/sparse_circuit_discovery/sparse_coding/interp_tools/utils/graphs.py", line 443, in neuronpedia_api
    response = requests.get(
  File "/opt/conda/lib/python3.10/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/conda/lib/python3.10/site-packages/requests/sessions.py", line 724, in send
    history = [resp for resp in gen]
  File "/opt/conda/lib/python3.10/site-packages/requests/sessions.py", line 724, in <listcomp>
    history = [resp for resp in gen]
  File "/opt/conda/lib/python3.10/site-packages/requests/sessions.py", line 191, in resolve_redirects
    raise TooManyRedirects(
requests.exceptions.TooManyRedirects: Exceeded 30 redirects.
```
